apiVersion: v1
kind: Service
metadata:
  name: voxscore-api
  labels:
    app.kubernetes.io/name: voxscore-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: voxscore-api
  ports:
    - name: http
      port: 3000
      targetPort: http
