apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voxscore
spec:
  rules:
    - host: voxscore.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: voxscore-api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: voxscore-frontend
                port:
                  number: 80
