apiVersion: v1
kind: ConfigMap
metadata:
  name: voxscore-api-config
data:
  TYPEORM_MIGRATIONS_RUN: 'true'
  AUTH_GOOGLE_MOCK_ENABLED: 'true'
  SWAGGER_ENABLED: 'true'
  CORS_ORIGINS: https://voxscore.local
